// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRyjy6F5CDBYg8hF3h0qek57i1ZBDmlig',
    appId: '1:457538846029:web:03d9e91767db257ab08b04',
    messagingSenderId: '457538846029',
    projectId: 'team-manager-792bd',
    authDomain: 'team-manager-792bd.firebaseapp.com',
    storageBucket: 'team-manager-792bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqO9IAy7C4zgvADmGd5frBFa5IiGfXew0',
    appId: '1:457538846029:android:0d2e09e12dba4223b08b04',
    messagingSenderId: '457538846029',
    projectId: 'team-manager-792bd',
    storageBucket: 'team-manager-792bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgKl1UFSAojJf_kG3zNsQKCvdDIVc5QuQ',
    appId: '1:457538846029:ios:2f851ff40571f93ab08b04',
    messagingSenderId: '457538846029',
    projectId: 'team-manager-792bd',
    storageBucket: 'team-manager-792bd.firebasestorage.app',
    iosBundleId: 'com.example.teamManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgKl1UFSAojJf_kG3zNsQKCvdDIVc5QuQ',
    appId: '1:457538846029:ios:2f851ff40571f93ab08b04',
    messagingSenderId: '457538846029',
    projectId: 'team-manager-792bd',
    storageBucket: 'team-manager-792bd.firebasestorage.app',
    iosBundleId: 'com.example.teamManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRyjy6F5CDBYg8hF3h0qek57i1ZBDmlig',
    appId: '1:457538846029:web:dcc97b8750efb1a4b08b04',
    messagingSenderId: '457538846029',
    projectId: 'team-manager-792bd',
    authDomain: 'team-manager-792bd.firebaseapp.com',
    storageBucket: 'team-manager-792bd.firebasestorage.app',
  );

}